### ISSUE TITLE
Missing coordinate system used for position and velocity vectors

### ISSUE THREAD

**Issue by keiranm24** [ReeceHumphreys/kesspy#11]
It would be useful for the user if the coordinate system used for the 3D vectors could be specified

**Comment by ReeceHumphreys** [comment]
Totally agree! Currently I am working on adding an API for specifying units using [pint](https://github.com/hgrecco/pint).

This definitely would be a good feature to have too. Will look into adding support for it in the 0.2 release.

**Comment by keiranm24** [comment]
Thanks for the response, I don't have any ideas off the top of my head. I was more meaning that it would be good to have the description of the vectors state which coordinate system they are based on.

Thanks for the info!
